---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)

if (!file.exists("activity.csv") )
    {
     dlurl <- 'http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip'
     download.file(dlurl,destfile='repdata%2Fdata%2Factivity.zip',mode='wb')  
     unzip('repdata%2Fdata%2Factivity.zip')
    }
data <- read.csv("activity.csv")

```

## What is mean total number of steps taken per day?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

num_steps<-aggregate(steps~date,data,sum)
     hist(num_steps$steps,
     col ="gray",
     main ="Number of steps taken per day",
     xlab = "Steps")

```
## Mean and Median
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

mean_steps<- mean(num_steps$steps)
cat("Mean",mean_steps,"\n")
median_steps<-median(num_steps$steps)
cat("Median",median_steps)

```
## What is the average daily activity pattern?
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

steps_interval<-aggregate(steps~interval,data,mean)
plot(steps_interval$interval,steps_interval$steps,
     type="l",
     xlab = "Interval",
     ylab = "Steps",
     main = "Average number of daily steps")

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)

max_steps<- steps_interval[which.max(steps_interval$steps),1]
cat("Max number of steps",max_steps)

```
## Imputing missing values
```{r setup, include= FALSE}
knitr::opts_chunk$set(echo=TRUE)

missing_values<-sum(is.na(data))
cat("Missing values",missing_values)

clean_data <- ddply(activity, ~interval, function(item) {

        item$steps[is.na(item$steps)] <- round(mean(item$steps, na.rm = TRUE));
        return(item);
    })
steps_cinterval<-aggregate(steps~interval,clean_data,mean)
plot(steps_cinterval$interval,steps_cinterval$steps,
     type="l",
     xlab = "Interval",
     ylab = "Steps",
     main = "Average number of daily steps")

```


## Are there differences in activity patterns between weekdays and weekends?
